### ISSUE TITLE
kflash_gui can not run in manjaro19

### ISSUE THREAD

**Issue by zsp1123** [sipeed/kflash_gui#13]
when click "Open File“，the app exit with an error like this:

icon path:/home/zsp/maixpy/kflash_gui/kflash_gui_data/assets/logo.png
config file path: /home/zsp/.config/kflash_gui/kflash_gui.conf
data path:/home/zsp/maixpy/kflash_gui/kflash_gui_data
2
error: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)>
/usr/lib/gio/modules/libgioremote-volume-monitor.so: undefined symbol: g_mount_operation_get_is_tcrypt_system_volume
Failed to load module: /usr/lib/gio/modules/libgioremote-volume-monitor.so
/usr/lib/gio/modules/libgioremote-volume-monitor.so: undefined symbol: g_mount_operation_get_is_tcrypt_system_volume
Failed to load module: /usr/lib/gio/modules/libgioremote-volume-monitor.so

(kflash_gui:2286): GdkPixbuf-WARNING **: 08:02:55.979: Cannot open pixbuf loader module file '/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders.cache': 没有那个文件或目录

This likely means that your installation is broken.
Try running the command
  gdk-pixbuf-query-loaders > /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders.cache
to make things work again for the time being.

(kflash_gui:2286): Gtk-WARNING **: 08:02:55.979: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.

(kflash_gui:2286): GdkPixbuf-WARNING **: 08:02:55.980: Cannot open pixbuf loader module file '/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders.cache': 没有那个文件或目录

This likely means that your installation is broken.
Try running the command
  gdk-pixbuf-query-loaders > /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders.cache
to make things work again for the time being.
**
Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /usr/share/icons/gnome/16x16/status/image-missing.png: 无法识别的图像文件格式 (gdk-pixbuf-error-quark, 3)
[1]    2285 abort (core dumped)  ./kflash_gui

**Comment by Neutree** [comment]
Actually we use Manjaro19 and Manjaro20 too, but not gnome, we use KDE, everything ok.

Maybe the problem yours is `Failed to load /usr/share/icons/gnome/16x16/status/image-missing.png`， so check your gnome icons theme

**Comment by Neutree** [comment]
I'll close this issue, if problem remain exists, you can reopen it
