### ISSUE TITLE
kflash_gui 1.5.5 not run win10 system

### ISSUE THREAD

**Issue by frezs** [sipeed/kflash_gui#14]
Run kflash_gui 1.5.5 from win10 system ,warning notice failed to execute script kflash_gui

**Comment by lyzdroid** [comment]
Metoo

**Comment by Neutree** [comment]
which version of Windows you use, Windows10 1909?

**Comment by lyzdroid** [comment]
Windows10 1903. At last I use kflash_gui v1.5 version and it works fine

**Comment by frezs** [comment]
yes, Windows10 1909 not works. But latst kflash_gui v1.5 works fine.

**Comment by machinehistories** [comment]
I also get the failed to execute script kflash_gui. I am running Windows 10 pro edition 2004.

**Comment by nnn112358** [comment]
kflash_gui 1.5.5 is Failed in windows10 1809, too.
kflash_gui 1.5 is OK.

**Comment by andreasderuiter** [comment]
Same here: 
kflash_gui 1.5.5 failed on windows10 1903.
kflash_gui 1.5 works fine.

**Comment by andreasderuiter** [comment]
Same here:
kflash_gui 1.5.5 failed on windows10 1903.
kflash_gui 1.5 works fine.

**Comment by Neutree** [comment]
Use v1.6.2, it works on windows10 1903, I'll close this issue, you can reopen if problem remain exists
