### ISSUE TITLE
Support for Maix Dock II

### ISSUE THREAD

**Issue by marcusobrien** [sipeed/kflash_gui#19]
I can not seem to get any firmware downloaded to the Maix Dock II, all other boards work including Maixduino, Maix Bit, Maix Dock.

The error is always fail to detect board - even though the 2 COM serial ports show up successfully in the Windows Device manager.

**Comment by Neutree** [comment]
Maix Dock II is linux board, should use other tools like etcher, see the doc please, https://wiki.sipeed.com/hardware/zh/maixII/M2/flash.html , and use translate tool at conner of the right top
