### ISSUE TITLE
DOWNLOAD should be UPLOAD

### ISSUE THREAD

**Issue by laurentopia** [sipeed/kflash_gui#2]
The big blue button at the bottom sends data UP to the board, not DOWN from the board.

**Comment by Neutree** [comment]
I think they have the same meaning. For example, in the Arduino IDE, the word upload is used. In other IDEs such as MDK, there are many tools that like to use the word download.

**Comment by laurentopia** [comment]
I guess the kendryte kflash also uses download, not worth you folks spending time with this each time you get their new version as It's really minor so i'll close it.
