### ISSUE TITLE
Does not work on Linux Mint 20.3

### ISSUE THREAD

**Issue by roglio** [sipeed/kflash_gui#20]
It seems requiring GLIBC_2.35 but on Mint there is only the 2.31.

$ ./kflash_gui
[40197] Error loading Python lib './kflash_gui/libpython3.8.so.1.0': dlopen: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found (required by ./kflash_gui/libpython3.8.so.1.0)

$ ldd --version
ldd (Ubuntu GLIBC 2.31-0ubuntu9.9) 2.31

**Comment by roglio** [comment]
Tested with release version 1.75. Btw, running from source code works. Maybe is a packaging problem.
It should be packaged with an earlier GLIBC version in order to work with more linux distributions.

**Comment by Neutree** [comment]
It's pack problem, linux use source code is the best way

**Comment by roglio** [comment]
Yes! Thanks. I did it that way and it worked. I also repackaged it locally.
