### ISSUE TITLE
Can't upload with v1.3.2 on macOS

### ISSUE THREAD

**Issue by kotobuki** [sipeed/kflash_gui#5]
Hi,

kflash_gui v1.2.5 works fine for me on macOS 10.15 Beta (19A512f) with my M5StickV (with m5stickV_Firmware_0630Fixed.kfpkg). However, I can't upload with the latest release version (i.e., v1.3.2). I want to share a screenshot for your reference.

<img width="420" alt="Screenshot 2019-07-19 17 18 53" src="https://user-images.githubusercontent.com/10932/61531297-62f0ab00-aa61-11e9-9468-20136204f6a2.png">

Anyway, thank you very much for developing such a useful tool. :wink:

**Comment by kotobuki** [comment]
This is an update. I just found that I can upload by choosing 'Sipeed Maix Bit (with Mic) for Board (was Auto) and 'Slow mode' for Speed mode (was Fast).

<img width="520" alt="Screenshot 2019-07-19 20 59 20" src="https://user-images.githubusercontent.com/10932/61533587-486e0000-aa68-11e9-856f-18a856c667e7.png">

**Comment by kotobuki** [comment]
This is an update.

I just found that I can upload by choosing 'Sipeed Maix Go ( open-ec & new CMSIS-DAP )3' for Board (was Auto) and 'Slow mode' for Speed mode (was Fast). Regarding the choice for the Board, I referred https://github.com/sipeed/kflash_gui/blob/v1.5.1/kflash_gui.py#L1032-L1047 and https://github.com/sipeed/kflash_gui/blob/v1.5.1/parameters.py#L28.

<img width="520" alt="スクリーンショット 2019-07-20 9 02 26" src="https://user-images.githubusercontent.com/10932/61572759-66c21300-aadd-11e9-9f8b-a1b68ceefa5c.png">

I also published an article in Japanese. I'll update once v1.5.x is released for macOS. 😉 

https://qiita.com/mayfair/items/d1a4ad360670c61ba0fa

**Comment by Neutree** [comment]
That's right, the M5StickV's download circuit is the same as Go's, actually the Maixduino、Bit with mic are also the same

**Comment by Neutree** [comment]
Select the slow mode because kflash.py upload ramrun occurs error when use 1.5Mbps baudrate, the slow mode use 115200bps to updalod ramrum and 1.5Mbps to upload firmware

**Comment by Orgmar** [comment]
MacOS's kernel driver don't support special baudrate, so must use "Slow mode"
