### ISSUE TITLE
kflash module not found

### ISSUE THREAD

**Issue by Archie1978** [sipeed/kflash_gui#8]
Hello, 

   I execute the commands like on documentation but  kflash not found :x
How I do make to corrected the problem ?

user@post:~/workspace/ia/sipeed/kflash_gui$ sudo pip3 install -r requirements.txt
[sudo] Mot de passe de user : 
The directory '/home/user/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/user/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied: bs4>=0.0.1 in /home/user/.local/lib/python3.6/site-packages (from -r requirements.txt (line 1))
Requirement already satisfied: PyQt5>=5.12.2 in /home/user/.local/lib/python3.6/site-packages (from -r requirements.txt (line 2))
Requirement already satisfied: pyserial>=3.4 in /home/user/.local/lib/python3.6/site-packages (from -r requirements.txt (line 3))
Requirement already satisfied: requests>=2.22.0 in /home/user/.local/lib/python3.6/site-packages (from -r requirements.txt (line 4))
Requirement already satisfied: urllib3>=1.25.3 in /home/user/.local/lib/python3.6/site-packages (from -r requirements.txt (line 5))
Requirement already satisfied: beautifulsoup4 in /home/user/.local/lib/python3.6/site-packages (from bs4>=0.0.1->-r requirements.txt (line 1))
Requirement already satisfied: PyQt5_sip<13,>=4.19.14 in /home/user/.local/lib/python3.6/site-packages (from PyQt5>=5.12.2->-r requirements.txt (line 2))
Requirement already satisfied: idna<2.9,>=2.5 in /home/user/.local/lib/python3.6/site-packages (from requests>=2.22.0->-r requirements.txt (line 4))
Requirement already satisfied: certifi>=2017.4.17 in /home/user/.local/lib/python3.6/site-packages (from requests>=2.22.0->-r requirements.txt (line 4))
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /home/user/.local/lib/python3.6/site-packages (from requests>=2.22.0->-r requirements.txt (line 4))
Requirement already satisfied: soupsieve>=1.2 in /home/user/.local/lib/python3.6/site-packages (from beautifulsoup4->bs4>=0.0.1->-r requirements.txt (line 1))
user@post:~/workspace/ia/sipeed/kflash_gui$ sudo pip3 install KFlash
The directory '/home/user/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/user/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied: KFlash in /home/user/.local/lib/python3.6/site-packages
Requirement already satisfied: pyelftools>=0.25 in /home/user/.local/lib/python3.6/site-packages (from KFlash)
Requirement already satisfied: enum34>=1.1.6 in /home/user/.local/lib/python3.6/site-packages (from KFlash)
Requirement already satisfied: pyserial>=3.4 in /home/user/.local/lib/python3.6/site-packages (from KFlash)
user@post:~/workspace/ia/sipeed/kflash_gui$ python3 kflash_gui.py 
Traceback (most recent call last):
  File "kflash_gui.py", line 25, in <module>
    from  kflash_py.kflash import KFlash
ModuleNotFoundError: No module named 'kflash_py.kflash'

**Comment by Neutree** [comment]
you can download bin file from [release page](https://github.com/sipeed/kflash_gui/releases)

> the problem you come across is not get submodule `git submodule update --init --recursive`

**Comment by Archie1978** [comment]
Well The binary work
