### ISSUE TITLE
kflash gui error - No such file or directory when trying to burn .kmodel packaged in .kfpkg

### ISSUE THREAD

**Issue by anku2424** [sipeed/kflash_gui#9]
Greetings, I was trying to burn my mobilenet v1 model that i trained via transfer learning on Sipeed Maix Dock. I packaged it in .kfpkg file with a flash-list.json specifying the address of the kmodel. I used the maixpy_v0.3.2_minimum.bin firmware. First i downloaded the firmware on the board and it successfully gets downloaded. But when i try to burn the .kfpkg file via kflash_gui i get this error - 
No such file or directory: 'C:\Users\user_name\AppData\Local\Temp\tgmslflsdag8kl\flash-list.json
How can i resolve this? TIA.

**Comment by Neutree** [comment]
this file is a temporary file created by kflash_gui, maybe you just need to try again? Or if your user_name is special?

**Comment by anku2424** [comment]
I've tried multiple times but it gives the same error. I'm using Windows 10 OS. It works properly  with other .kfpkg files that i downloaded from the internet, but for this specific .kfpkg which i made myself, it does not work. But i am not able to understand what i did wrong.

**Comment by Neutree** [comment]
upload kfpkg made by you here, I'll check for you
